### ISSUE TITLE
Export Failed

### ISSUE THREAD

**Issue by eleseberg** [yoyokits/BarChartRaceNet#4]
When running the exe I am able to input a couple of different example CSV files. I can see the data on screen and move through the data overtime.
On any of these files when I click on Export chart to video an error is shown. "Export Failed. Error: The system cannot find the file specified."

Windows 10 Home 20H2
.NET Core 3.1 Desktop Runtime (v3.1.18)
Initial Pre-release 0.1.0.0 Alpha

![image](https://user-images.githubusercontent.com/568313/131218857-804ad6d8-df93-4ed1-8fc8-733319bb9b21.png)

**Comment by yoyokits** [comment]
Thank you for the report.  I am sorry for the late response.
The problem is ffmpeg.exe not found.
We can download it from https://ffbinaries.com/downloads, extract and put the ffmpeg.exe on the application folder.
I have improved it by adding the warning.
I will create a new release that include ffmpeg.exe.

**Comment by yoyokits** [comment]
This issue is solved in newest release:
[v0.1.0.1-beta](https://github.com/yoyokits/BarChartRaceNet/releases/tag/v0.1.0.1-beta)
Please inform me if it is not working.
